# Generated by Django 4.1.4 on 2023-01-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='Фамилия_Имя')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserEvents', to='eventsapp.customuser')),
            ],
        ),
    ]
